# Generated by Django 3.2.7 on 2022-01-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0007_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
