# Generated by Django 3.2.7 on 2022-01-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0011_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
