# Generated by Django 3.2.7 on 2022-01-11 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0012_remove_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
