# Generated by Django 3.2.7 on 2022-01-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Picked By Courier', 'Picked By Courier'), ('On The Way', 'On The Way')], default='Not Selected', max_length=155),
        ),
    ]
