# Generated by Django 3.2.7 on 2022-01-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Picked By Courier', 'Picked By Courier'), ('On The Way', 'On The Way')], default='Pending', max_length=155, null=True),
        ),
    ]
