# Generated by Django 4.0.3 on 2022-04-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
