# Generated by Django 4.0.3 on 2022-04-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0019_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hotel_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apk.hotels'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
