# Generated by Django 4.0.3 on 2022-04-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0020_product_hotel_name_alter_hotels_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='category',
        ),
    ]
