# Generated by Django 4.0.3 on 2022-04-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0021_remove_hotels_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
