# Generated by Django 4.0.3 on 2022-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0022_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='table',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
