# Generated by Django 4.0.3 on 2022-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0023_hotels_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='primary_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
