# Generated by Django 4.0.3 on 2022-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0026_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
