# Generated by Django 4.0.3 on 2022-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0027_alter_table_date_alter_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tables',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
