# Generated by Django 4.0.4 on 2022-05-07 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0033_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
