# Generated by Django 4.0.4 on 2022-05-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apk', '0037_alter_reviews_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='time',
            field=models.TimeField(default='08:46:58'),
        ),
    ]
